server:  port: 8282

spring:
  application:
    name: gateway
 

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**        - id: book-service          uri: lb://book-service          predicates:            - Path=/book/**  

eureka:  client:    register-with-eureka: true    fetch-registry: true    service-url:      defaultZone: http://localhost:8761/eureka/  instance:    hostname: localhost